name: Build and Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

# To test workflow updates you need to work in a branch directly on viam-modules/sensirion
# and tag your working branch instead of @main in any viam-modules/sensirion "uses" below.
# Don't forget to tag back to @main before merge.

jobs:
  # test:
  #   uses: ./.github/workflows/test.yml

  publish:
    # needs: test
    strategy:
      matrix:
        include:
          - arch: buildjet-8vcpu-ubuntu-2204
            platform: linux/amd64
            goarch: amd64
          - arch: buildjet-8vcpu-ubuntu-2204-arm
            platform: linux/arm64
            goarch: arm64
          - arch: buildjet-8vcpu-ubuntu-2204-arm
            platform: linux/arm32v6
            goarch: arm
            goarm: '6'

    runs-on: ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Build module
      run: GOARCH=${{ matrix.goarch }} GOARM=${{ matrix.goarm }} make module

    - name: Upload sensirion module to registry
      uses: viamrobotics/upload-module@main
      with:
        meta-path: meta.json
        module-path: bin/module.tar.gz
        platform: ${{ matrix.platform }}
        version: ${{ github.event_name == 'push' && github.ref_name || '' }}
        key-id: ${{ secrets.VIAM_DEV_API_KEY_ID }}
        key-value: ${{ secrets.VIAM_DEV_API_KEY }}
